# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/orders", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: "Fixing TV",
      note: "it's not German TV",
      description: "stopped suddenly"
    }
  end

  let(:invalid_attributes) do
    {
      title: 1,
      note: "German TV",
      description: nil
    }
  end
  let!(:user) { create(:user) }
  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    { "Authorization" => token_generator(user_id: user.id) }
  end

  describe "GET /index" do
    let(:order) { create(:order) }
    it "renders a successful response" do
      get api_v1_orders_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    context "When order exists" do
      let(:order) { create(:order) }

      it "renders a successful response" do
        get api_v1_order_url(order), headers: valid_headers, as: :json
        expect(response).to be_successful
        serialized_object = serialized_object_to_json(object: generic_serialized_object(object: order,
                                                                                        serializer: "OrderSerializer"))
        expect(json[:order]).to eq(serialized_object)
      end
    end
    context "When order does not exist" do
      it "renders ActiveRecord::RecordNotFound" do
        get "/api/v1/orders/1", headers: valid_headers, as: :json
        expect(json[:errors]).to eq({ "message" => "Couldn't find Order with 'id'=1" })
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Order" do
        expect do
          post api_v1_orders_url,
               params: { order: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Order, :count).by(1)
      end

      it "renders a JSON response with the new order" do
        post api_v1_orders_url,
             params: { order: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
        serialized_object = serialized_object_to_json(object: generic_serialized_object(object: Order.last,
                                                                                        serializer: "OrderSerializer"))

        expect(json[:order]).to eq(serialized_object)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Order" do
        expect do
          post api_v1_orders_url,
               params: { order: invalid_attributes }, as: :json
        end.to change(Order, :count).by(0)
      end

      it "renders a JSON response with errors for the new order" do
        post api_v1_orders_url,
             params: { order: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    let!(:order) { create(:order) }
    context "with valid parameters" do
      let(:new_attributes) do
        {
          title: "New title",
          note: "it's not German TV",
          description: "stopped suddenly"
        }
      end
      it "updates the requested order" do
        patch api_v1_order_url(order),
              params: { order: new_attributes }, headers: valid_headers, as: :json
        order.reload
        expect(order.title).to eq(new_attributes[:title])
      end

      it "renders a JSON response with the order" do
        patch api_v1_order_url(order),
              params: { order: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
        order.reload
        serialized_object = serialized_object_to_json(object: generic_serialized_object(object: order,
                                                                                        serializer: "OrderSerializer"))
        expect(json[:order]).to eq(serialized_object)
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the order" do
        patch api_v1_order_url(order),
              params: { order: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:order) { create(:order) }

    it "destroys the requested order" do
      expect do
        delete api_v1_order_url(order), headers: valid_headers, as: :json
      end.to change(Order, :count).by(-1)
    end
  end
end
